"""empty message

Revision ID: 194851f460a6
Revises: e14f186250a1
Create Date: 2023-08-12 17:49:25.812799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194851f460a6'
down_revision = 'e14f186250a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
